- hosts: httpservers
  tasks:
    - name: Installe httpd
      become: true
      dnf:
         name: 
           - httpd
         state: latest
    - name: Configuration du firewall de base
      become: true
      ansible.posix.firewalld:
         service: http
         zone: public
         immediate: yes
         permanent: yes
         state: enabled
    - name: Copy config
      become: true
      copy:
       src: '{{ ansible_host }}/'
       dest: /
    - name: Delete default welcome
      become: true
      shell: 
        cmd: mv -f /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.not || true
    - name: Enlever SELinux
      become: true
      shell: 
        cmd: setenforce 0 || true
    - name: Lance httpd
      become: true
      service:
         name: httpd
         state: reloaded
         enabled: true
